version: 2.1
orbs:
  barkendeploy: navikt/barkendeploy@dev:master
parameters:
  deploy_branch:
    type: boolean
    default: false
jobs:
  build:
    docker:
      - image: "circleci/node:latest"
    steps:
      - checkout
      - setup_remote_docker
      - barkendeploy/init
      - run:
          name: Update npm
          command: 'sudo npm install -g npm'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Run npm install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Test
          command: npm run test
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Bygg
          command: npm run nais-build
      - barkendeploy/docker-build
      - barkendeploy/docker-login
      - barkendeploy/docker-push
workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          context: barkendeploy
          filters:
            branches:
              only: master
      - barkendeploy/deployment:
          deployments:
            - barkendeploy/deploy-create:
                cluster: dev-fss
           # - barkendeploy/deploy-create:
           #     cluster: prod-sbs
          context: barkendeploy
          requires:
            - build
  test_branch:
    unless: << pipeline.parameters.deploy_branch >>
    jobs:
      - run_tests:
          filters:
            branches:
              ignore: master
  build_branch:
    when: << pipeline.parameters.deploy_branch >>
    jobs:
      - build:
          context: barkendeploy
          filters:
            branches:
              ignore: master
      - barkendeploy/deployment:
          deployments:
            - barkendeploy/deploy-create:
                cluster: dev-fss
          context: barkendeploy
          requires:
            - build